language: rust
cache: cargo
install:
  - cargo build --verbose
  - rustup component add rustfmt clippy-preview
script:
  - cargo build --verbose --all
  - cargo test --verbose --all -- --test-threads=1
  - cargo fmt --all -- --check
  # https://github.com/rust-lang/rust/issues/59909
  # - cargo clippy -- -D warnings
