[package]
name = "vole"
version = "0.1.0"
authors = ["Martin Indra"]
edition = "2018"

[dependencies]
rand = "0.6.5"
clap = "2.33"
chrono = "0.4"
lazy_static = "1.0.0"
fnv = "1.0.6"
dirs = "1.0.5"

[dev-dependencies]
assert_cmd = "0.11"
regex = "1"
